name: Deploy Angular App to Azure Static Web Apps

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  build_and_deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Inject production secrets
        run: |
          for file in src/environments/environment.ts src/environments/environment.dev.ts src/environments/environment.prod.ts; do
            echo "export const environment = {" > $file
            echo "  production: false," >> $file
            echo "  serviceUrl: '${{ secrets.SERVICE_URL }}'," >> $file
            echo "  apiKey: '${{ secrets.API_KEY }}'" >> $file
            echo "};" >> $file
          done

      - name: Build Angular app (dev)
        run: npm run build -- --configuration development

      - name: Copy staticwebapp.config.json to output
        run: cp staticwebapp.config.json dist/store/browser/

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          action: "upload"
          app_location: "/" 
          output_location: "dist/store/browser"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
